export const SEARCH_PHRASE_CHANGED = "SEARCH_PHRASE_CHANGED";
export const IS_FOCUSED_CHANGED = "IS_FOCUSED_CHANGED";
export const FAVOURITES = {
  REMOVE: "REMOVE_FAVOURITES",
  ADD: "ADD_TO_FAVOURITES"
};
